### ISSUE TITLE
Identify and fix cause of crash when calling `Pixels::new`

### ISSUE THREAD

**Issue by AnEnigmaticBug** [AnEnigmaticBug/wolfenstein_lite#5]
This demo uses `pixels` for drawing stuff to a window. On some systems, the demo crashes upon launch. The offending line calls `Pixels::new`. I've mentioned the specifics in their repo ([here](https://github.com/parasyte/pixels/issues/36#issuecomment-753332655)).

**Comment by parasyte** [comment]
The panic occurs in your application because you are unwrapping the `Result` type returned by `pixels::new()`: https://github.com/AnEnigmaticBug/wolfenstein_lite/blob/fdc3711e7f09a8072af1f44a998daef2dce4be17/src/main.rs#L30

You can instead just inspect the error type and report a useful error message to the user. E.g.

```rust
let pixels = match Pixels::new(SCR_WD, SCR_HT, surf) {
    Err(pixels::Error::AdapterNotFound) |
    Err(pixels::Error::DeviceNotFound(_)) => panic!("Graphics Adapter or Device Not Found ... Did you install a driver?"),
    _ => (),
}
```

I guess this example isn't really a useful error message. Also it just panics instead of displaying anything friendly, which will depend on which windowing system you are using. [`native-dialog`](https://crates.io/crates/native-dialog) might be better...

**Comment by AnEnigmaticBug** [comment]
I know I placed a panic there :). I really like your suggestion about showing the user a dialog in case of errors. Thanks.

**Comment by AnEnigmaticBug** [comment]
The issue is related to VirtualBox and not `pixels`. It doesn't support Vulkan properly. Both `vkcube` and `vulkaninfo` failed in the VM.

So, I guess I can't do anything other than reporting the issue.
